# Generated by Django 4.2.7 on 2024-02-05 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_alter_produto_quantidade_estoque'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='codigo_barras',
            field=models.CharField(default=0, max_length=50, unique=True),
        ),
    ]
