# Generated by Django 4.2.7 on 2024-02-05 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0006_alter_produto_codigo_barras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='codigo_barras',
            field=models.CharField(default='', max_length=20),
        ),
    ]
