# Generated by Django 4.2.7 on 2023-11-23 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='visivel',
            new_name='disponivel',
        ),
    ]
