# Generated by Django 4.2.7 on 2023-11-28 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proprietario',
            fields=[
                ('funcionario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='funcionarios.funcionario')),
            ],
            bases=('funcionarios.funcionario',),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='cpf_funcionario',
            field=models.CharField(default='000.000.000-00', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='telefone_funcionario',
            field=models.CharField(default='(00)00000-0000', max_length=20),
        ),
    ]
