# Generated by Django 4.2.7 on 2023-11-28 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_proprietario_funcionario_cpf_funcionario_and_more'),
        ('administracao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loja',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='loja',
            name='id_dono',
        ),
        migrations.AddField(
            model_name='loja',
            name='id_proprietario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='funcionarios.proprietario'),
        ),
    ]
