# Generated by Django 4.2.7 on 2023-11-28 01:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administracao', '0002_remove_loja_categoria_remove_loja_id_dono_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loja',
            name='id_proprietario',
        ),
        migrations.AddField(
            model_name='loja',
            name='usuario_responsavel',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loja',
            name='nome_loja',
            field=models.CharField(max_length=100),
        ),
    ]
