# Generated by Django 4.2.7 on 2024-02-05 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_remove_venda_produtos_alter_venda_funcionario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='itens',
        ),
        migrations.AddField(
            model_name='itemvenda',
            name='venda',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendas.venda'),
        ),
    ]
