# Generated by Django 4.2.7 on 2024-02-05 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_remove_venda_itens_itemvenda_venda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='cliente',
        ),
    ]
