# Generated by Django 4.2.7 on 2024-02-05 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0004_remove_venda_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='formas_pagamento',
            field=models.TextField(blank=True, null=True),
        ),
    ]
